### PR TITLE
feat(FileUpload): Add @vue/compat configuration to vue 3

### PR DESCRIPTION
**Pull request by fanta759**

### CODE REVIEW

**Comment by sgloe** [comment]
This would definitely help!

**Comment by sgloe** [comment]
@lian-yue To clarify here: We need this, when you have @vue/compat running in MODE: 2 for the whole application. Your vue-upload-component is already Vue3 ready and in Compat MODE 2, we need to explicitly define the components, that are ready for 3. Otherwise the v-model does not work and files does not get updated in the parent component. Would be nice if we can see this merge in the next release, because your component is awesome and helps me and many others alot! :)

[A not working examplge with Bootsrap-Vue in Compat Mode 
](https://stackblitz.com/edit/bootstrap-vue-with-compat-cbexvd?file=components%2FHelloBootstrap.vue)

**Comment by sgloe** [comment]
Great! Thanks all!

**Comment by lian-yue** [comment]
https://www.npmjs.com/package/vue-upload-component/v/3.1.17
https://github.com/lian-yue/vue-upload-component/tree/v3.1.17

@sgloe

**Pull request merged**
